# -*- coding: utf-8 -*-
"""db_base.py — Protocol-интерфейс подсистемы хранения данных СПА.

Определяет контракт, которому должен удовлетворять любой бэкенд БД.
Использование typing.Protocol вместо ABC позволяет применять type-checker
и isinstance()-проверки без наследования от базового класса.
"""
from __future__ import annotations

from datetime import datetime
from typing import Optional, Protocol, runtime_checkable

from .schema import EquipmentRecord, PredictionRecord, TelemetryMeasurement


@runtime_checkable
class DatabaseProtocol(Protocol):
    """Интерфейс бэкенда хранения данных."""

    # ===== Equipment =====
    def upsert_equipment(self, record: EquipmentRecord) -> None: ...
    def list_equipment(self) -> list[dict]: ...

    # ===== Predictions =====
    def has_predictions(self) -> bool: ...
    def insert_prediction(self, record: PredictionRecord) -> None: ...
    def latest_predictions(self, limit: int = 100) -> list[dict]: ...
    def predictions_history(self, machine_id: str, limit: int = 200) -> list[dict]: ...
    def all_machines_overview(self) -> list[dict]: ...

    # ===== Telemetry =====
    def insert_raw_measurement(self, measurement: TelemetryMeasurement) -> None: ...
    def latest_raw_measurements(self, machine_id: str, limit: int = 50) -> list[dict]: ...
    def insert_hourly_aggregate(self, machine_id: str, window_end: datetime,
                                features: dict) -> None: ...
    def get_sensor_averages(self, machine_id: str, days: int = 7) -> dict: ...

    # ===== Seeding =====
    def bulk_insert_for_seed(self, telemetry_rows: list[tuple],
                             prediction_rows: list[tuple]) -> None: ...

    # ===== Incidents =====
    def get_open_incident(self, machine_id: str) -> Optional[dict]: ...
    def open_incident(self, machine_id: str, opened_at: datetime,
                      probability: float, rul_days: float, threshold: float,
                      severity: str = "medium") -> int: ...
    def update_open_incident(self, incident_id: int, probability: float,
                             rul_days: float, peak_severity: str = "medium") -> None: ...
    def close_incident(self, incident_id: int, closed_at: datetime) -> None: ...
    def list_incidents(self, status: Optional[str] = None,
                       machine_type: Optional[str] = None,
                       limit: int = 200) -> list[dict]: ...
    def incidents_summary(self) -> dict: ...

    # ===== Alerts =====
    def get_alerts_count(self) -> int: ...
    def last_alert_for_machine(self, machine_id: str) -> Optional[dict]: ...
    def get_alert(self, alert_id: int) -> Optional[dict]: ...
    def insert_alert(self, incident_id: Optional[int], machine_id: str,
                     sent_at: datetime, recipient: str, subject: str,
                     body: str, channel: str, status: str,
                     severity: str = "medium",
                     group_key: Optional[str] = None,
                     grouped_count: int = 1,
                     error: Optional[str] = None) -> int: ...
    def list_alerts(self, limit: int = 100) -> list[dict]: ...

    # ===== Notification settings =====
    def get_notification_settings(self) -> dict: ...
    def save_notification_settings(self, *, email_enabled: bool, sms_enabled: bool,
                                   push_enabled: bool, email: str, phone: str,
                                   failure_threshold: float) -> dict: ...

    # ===== Lifecycle =====
    def close(self) -> None: ...
